export enum AsyncInteractionType {
    PORTAL_GET_ALL_SERIES = 'PORTAL_GET_ALL_SERIES',
    PORTAL_GET_DETAILED_SERIES = 'PORTAL_GET_DETAILED_SERIES',
    PORTAL_GET_SEASON_EPISODES = 'PORTAL_GET_SEASON_EPISODES',
    PORTAL_GET_ALL_PROVIDOR_LINKS = 'PORTAL_GET_ALL_PROVIDOR_LINKS',
    PORTAL_GET_EPISODE_INFO = 'PORTAL_GET_EPISODE_INFO',
    VIDEO_OPEN_VIDEO = 'VIDEO_OPEN_VIDEO',
}
