export enum AsyncInteractionType {
    PORTAL_GET_ALL_SERIES = 'PORTAL_GET_ALL_SERIES',
    PORTAL_GET_DETAILED_SERIES = 'PORTAL_GET_DETAILED_SERIES',
    PORTAL_GET_SEASON_EPISODES = 'PORTAL_GET_SEASON_EPISODES',
    PORTAL_GET_EPISODE_INFO = 'PORTAL_GET_EPISODE_INFO',
}
